### ISSUE TITLE
udp_dstip issue when switching between tengiga 0 and 1

### ISSUE THREAD

**Issue by mbrueckner-psi** [slsdetectorgroup/slsDetectorPackage#77] opened 2020-02-13 10:55 UTC
after switching several times from tengiga 1 to 0 and back, rx_hostname in a config file is not enough to specify the udp dst.
Steps to reproduce:
./sls_detector_put tengiga 1
./sls_detector_put tengiga 0
...
./sls_detector_put tengiga 1
./sls_detector_put tengiga 1

./sls_detector_put config beb_34_1g.config
./sls_detector_get udp_dstip
udp_dstip 10.1.1.110

**Comment by thattil** [comment] 2020-02-19 05:37
Hi Martin

I believe we discussed this before. This was the issue when we removed udp details in shm. (Issue: switching between tengiga 1 and tengiga 0). You need to then specify the 1g udpip explicitly, when you switch back to 1g, because it think it already has a customised dest usp ip.

But we can discuss this when I am back.

Cheers
Dhanya


On 14 Feb 2020 19:45, mbrueckner-psi <notifications@github.com> wrote:

after switching several times from tengiga 1 to 0 and back, rx_hostname in a config file is not enough to specify the udp dst.
Steps to reproduce:
./sls_detector_put tengiga 1
./sls_detector_put tengiga 0
...
./sls_detector_put tengiga 1
./sls_detector_put tengiga 1

./sls_detector_put config beb_34_1g.config
./sls_detector_get udp_dstip
udp_dstip 10.1.1.110

**Comment by thattil** [comment] 2020-02-28 08:34
In 1G, udp destination ip is usually not configured. It is picked up from rx_hostname if no value assigned to it. This works.
When switching to 10g, the udp destination ip is overwritten and this work as well.
When switching back to 1g, the udp destination ip is not empty (hence not picked up from rx_hostname).
Therefore, one has to specify the udp destination ip in the 1g config file (if you plan to switch between 1g and 10g, which is normally not the case (just for testing)).
This is what we had agreed on. I will be closing this issue, unless you have another way to resolve this.

**Closed by thattil** 2020-02-28 08:34 UTC
