### ISSUE TITLE
G2: rxr stuck after multiple acquires

### ISSUE THREAD

**Issue by jiaguozhang** [slsdetectorgroup/slsDetectorPackage#143] opened 2020-08-24 14:19 UTC
##### *Describe the bug

Receiver stoped and shut down after multiple data acquisitions.

##### Expected behavior

Receiver not to stop during data acquision.

##### To Reproduce

Burst mode internal timing.
Number of frames: 2720
Number of triggers: 100
Number of data acquisions (sls_detector_acquire): 3501
Exposure: 0
Period: 0
External trigger: 10 Hz

Total frames expected: 3501*2720*100 ~ 1 G frames

##### Screenshots

Receiver print out:
INFO: Stopping Receiver
INFO: Status: Transmitting
INFO: Shut down of UDP port 50001

then if do 
sls_detector_get rx_stop  --> no response
has to kill receiver and then restart detector server when it happens

How often it happens? --> after running sls_detector_acquire for 800 times (not a fixed number)

**Comment by thattil** [comment] 2020-08-31 16:04
unable to reproduce. Ran script in different ways multiple times with 3501 acquires each. And a final one using the original script (python and wave generator code included) on original rxr, client and detector. Closing issue until reproduced again.

**Closed** 2020-08-31 16:05 UTC
Labels: action - Bug, priority - Super high, status - resolved
